Homework#1/account/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = 'account'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('reg/', views.AccountRegistrationView.as_view(), name='reg'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),

    path('about/<str:username>/', views.AboutProfileView.as_view(), name='about'),
    path('edit/', views.EditProfileView.as_view(), name='edit')
]

Homework#1/main/urls.py
from django.urls import path
from . import views

app_name = 'main'

urlpatterns = [
    path('', views.Main.as_view(), name='home'),
    path('delete_blog/<int:blog>',views.delete_blog, name='deleteblog'),
    path('edit_blog/<int:blog>',views.EditBlog.as_view(), name='editblog'),
    path('edit_blog/delete_image/<int:blog>/<int:image>', views.delete_image, name='deleteimage'),
]

Homework#1/templates/parts_of_base/footer.html
<div class="footer mt-5 px-5">
    <div class="row">
        <div class="col-4"></div>
        <div class="col-4"></div>
        <div class="col-4 text-center">
            <h3>Выполнил: Кокоев Артур</h3>
            <h3>Группа: РТ5-51</h3>
        </div>
    </div>
</div>

Homework#1/templates/parts_of_base/header.html
<header class="container py-2">
    <nav class="navbar nav-pills">
        <a class="nav-item nav-link" id="home" href="{% url 'main:home' %}">Главная</a>

        {% if request.user.is_authenticated %}
            <li class="nav-item dropdown" style="list-style-type: none">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                   data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    {{ request.user.username }}
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <a class="dropdown-item" href="{% url 'account:about' request.user.username %}" id="profile">Профиль</a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="{% url 'account:logout' %}?next=/">Выйти</a>
                </div>
            </li>
        {% else %}
            <li class="nav-item" style="list-style-type: none">
                <a class="nav-link" href="{% url 'account:login' %}" id="login_btn">
                    Войти
                </a>
            </li>
        {% endif %}
    </nav>
</header>