Homework#1/account/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = 'account'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('reg/', views.AccountRegistrationView.as_view(), name='reg'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),

    path('about/<str:username>/', views.AboutProfileView.as_view(), name='about'),
    path('edit/', views.EditProfileView.as_view(), name='edit')
]

Homework#1/main/urls.py
from django.urls import path
from . import views

app_name = 'main'

urlpatterns = [
    path('', views.Main.as_view(), name='home'),
    path('delete_blog/<int:blog>',views.delete_blog, name='deleteblog'),
    path('edit_blog/<int:blog>',views.EditBlog.as_view(), name='editblog'),
    path('edit_blog/delete_image/<int:blog>/<int:image>', views.delete_image, name='deleteimage'),
]

Homework#1/main/models.py
from django.contrib.auth.models import User
from django.db import models
from django.utils.safestring import mark_safe

class Blog(models.Model):
    title = models.CharField(max_length=100, verbose_name='Название')
    description = models.TextField(max_length=1500, verbose_name='Текст', blank=True)
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Создано')
    updated_at = models.DateTimeField(auto_now=True, verbose_name='Обновлено')

    def display_my_safefield(self):
        return mark_safe(self.description)

    class Meta:
        verbose_name = "Блог"
        verbose_name_plural = "Блоги"

    def __str__(self):
        return "Блог: {}".format(self.title)

class ImagesForBlog(models.Model):
    blog = models.ForeignKey(Blog, on_delete=models.CASCADE, verbose_name='Изображения', blank=True)
    image = models.ImageField(upload_to='static/images/blogs/%m', verbose_name='Изображение')

    class Meta:
        verbose_name = "Изображения"
        verbose_name_plural = "Изображения для блогов"

    def __str__(self):
        return "Изоброжения для {}".format(self.blog.title)

class CommentsForBlog(models.Model):
    blog = models.ForeignKey(Blog, on_delete=models.CASCADE, verbose_name='Комментарии', blank=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE,verbose_name='Комментатор')
    text = models.TextField(max_length=800, verbose_name='Текст')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Создано')

    class Meta:
        verbose_name = "Комментарий"
        verbose_name_plural = "Комментарии"

    def __str__(self):
        return "Комментарии для {}".format(self.blog.title)

Homework#1/main/forms.py
from django import forms
from .models import Blog, ImagesForBlog

class BlogForm(forms.ModelForm):
    class Meta:
        model = Blog
        fields = ('title','description')

class ImagesForBlogForm(forms.ModelForm):
    class Meta:
        model = ImagesForBlog
        fields = ('image','blog')

Homework#1/main/views.py
from django.shortcuts import render, redirect
from django.views.generic import View, ListView
from .models import Blog, ImagesForBlog, CommentsForBlog
from django.core.paginator import Paginator
from .forms import BlogForm,ImagesForBlogForm


def delete_blog(request,blog):
    Blog.objects.get(pk=blog).delete()
    return redirect('main:home')


def delete_image(request,image,blog):
    ImagesForBlog.objects.get(pk=image).delete()
    return redirect('main:editblog', blog)


class Main(View):
    template_name = 'main.html'


    def get(self, request, *args, **kwargs):
        blogs = []
        for blog in Blog.objects.all():
            blogs.append({
                'data': blog,
                'images': ImagesForBlog.objects.filter(blog=blog.id),
            })
        for blog in blogs:
            blog['comments'] = reversed(CommentsForBlog.objects.filter(blog=blog['data'].id))

        page = request.GET.get('page')
        if not page:
            page = 1

        p = Paginator(list(reversed(blogs)), 3)

        return render(request, self.template_name, {
            'page': 'home',
            'title': 'Блог | Главная',
            'blogs': p.page(page),
            'blogForm': BlogForm,
            'imagesForBlogForm': ImagesForBlogForm,
            'pagnav': p.page_range
        })

    def post(self,request, *args, **kwargs):
        if request.POST.get('is_comment', False):
            comment = CommentsForBlog(blog=Blog.objects.get(pk=request.POST['blog']), user=request.user, text=request.POST['text'])
            comment.save()
            return redirect('main:home')
        else:
            blog = Blog(title=request.POST['title'], description=request.POST['description'])
            blog.save()
            if request.FILES:
                for img in request.FILES.keys():
                    image = ImagesForBlog(image=request.FILES[img], blog=blog)
                    image.save()
            return redirect('main:home')

class EditBlog(View):
    template_name = 'blog/edit.html'

    def get(self, request, blog, *args, **kwargs):
        blog = Blog.objects.get(pk=blog)
        return render(request,self.template_name, {
            'title': 'Блог | {}'.format(blog.title),
            'blog': blog,
            'images': ImagesForBlog.objects.filter(blog=blog)
        })

    def post(self, request, blog, *args, **kwargs):
        b = Blog.objects.get(pk=blog)
        b.title = request.POST['title']
        b.description = request.POST['description']
        b.save()
        if request.FILES:
            for img in request.FILES.keys():
                image = ImagesForBlog(image=request.FILES[img], blog=b)
                image.save()
        return redirect('main:home')

Homework#1/main/templates/blog/blog.html
<div class="col-8">
    <div class="card my-3 blog" id="{{ blog.data.id }}">
        <div class="card-header">
            {% if request.user.is_superuser %}
                <p style="position: absolute; width: 150px; right: 10px">
                    <a href="{% url 'main:editblog' blog.data.id %}" class="btn btn-warning">Изменить</a>
                    <a href="{% url 'main:deleteblog' blog.data.id %}" class="btn btn-danger">X</a>
                </p>
            {% endif %}
        <h3>{{blog.data.title}}</h3>
        </div>
        <div class="card-body px-5">
            <p>{{blog.data.display_my_safefield }}</p>
            <div class="images-slider">
                {% for img in blog.images %}
                <div class="slider-img mx-3">
                    <a href="{{img.image.url}}">
                        <img src="{{img.image.url}}" height="500">
                    </a>
                </div>
                {% endfor %}
            </div>
        </div>
        <div class="card-footer">
            <p class="text-right text-muted m-0 p-0">Создано: {{ blog.data.created_at }} | Изменено: {{ blog.data.updated_at }}</p>
        </div>
    </div>
</div>
<div class="col-4">
    <div class="card my-3 comments" id="comment{{ blog.data.id }}">
        <div class="card-header">
            <b>Комментарии</b>
        </div>
        <div class="card-body" style="overflow: scroll">
            <ul class="p-0">
                {% for comment in blog.comments %}
                    <li style="list-style-type: none">
                        <div class="card mb-3">
                            <div class="card-header p-1"><b><a href="{% url 'account:about' comment.user %}">{{ comment.user }}</a></b></div>
                            <div class="card-body p-2">{{ comment.text }}</div>
                            <div class="card-footer p-1"><p class="text-muted text-right p-0 m-0">{{ comment.created_at }}</p></div>
                        </div>
                    </li>
                {% empty %}
                    Нет комментариев
                {% endfor %}
            </ul>
        </div>
        <div class="card-footer">
            {% if request.user.is_authenticated %}
                <form action="{% url 'main:home' %}" method="post">
                    {% csrf_token %}
                    <input type="text" hidden value="True" name="is_comment">
                    <input type="text" hidden value="{{ blog.data.id }}" name="blog">
                    <textarea name="text" cols="30" rows="2" class="form-control" placeholder="Комментировать"></textarea>
                    <p class="p-0 m-0 text-right"><input type="submit" value="Отправить" class="btn btn-success btn-sm my-1"></p>
                </form>
            {% else %}
                <a href="{% url 'account:login' %}">Авторизируйтесь</a> чтобы оставить комментарий.
            {% endif %}
        </div>
    </div>
</div>

Homework#1/main/templates/blog/edit.html
{% extends 'base.html' %}
{% block content %}
    <div class="container" style="margin-bottom: calc(120px + 3rem)!important;">
    {% include 'forms/editblog.html' %}
    </div>
{% endblock %}