Homework#1/main/urls.py
from django.urls import path
from . import views

app_name = 'main'

urlpatterns = [
    path('', views.Main.as_view(), name='home'),
    path('delete_blog/<int:blog>',views.delete_blog, name='deleteblog'),
    path('edit_blog/<int:blog>',views.EditBlog.as_view(), name='editblog'),
    path('edit_blog/delete_image/<int:blog>/<int:image>', views.delete_image, name='deleteimage'),
]

Homework#1/main/models.py
from django.contrib.auth.models import User
from django.db import models
from django.utils.safestring import mark_safe

class Blog(models.Model):
    title = models.CharField(max_length=100, verbose_name='Название')
    description = models.TextField(max_length=1500, verbose_name='Текст', blank=True)
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Создано')
    updated_at = models.DateTimeField(auto_now=True, verbose_name='Обновлено')

    def display_my_safefield(self):
        return mark_safe(self.description)

    class Meta:
        verbose_name = "Блог"
        verbose_name_plural = "Блоги"

    def __str__(self):
        return "Блог: {}".format(self.title)

class ImagesForBlog(models.Model):
    blog = models.ForeignKey(Blog, on_delete=models.CASCADE, verbose_name='Изображения', blank=True)
    image = models.ImageField(upload_to='static/images/blogs/%m', verbose_name='Изображение')

    class Meta:
        verbose_name = "Изображения"
        verbose_name_plural = "Изображения для блогов"

    def __str__(self):
        return "Изоброжения для {}".format(self.blog.title)

class CommentsForBlog(models.Model):
    blog = models.ForeignKey(Blog, on_delete=models.CASCADE, verbose_name='Комментарии', blank=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE,verbose_name='Комментатор')
    text = models.TextField(max_length=800, verbose_name='Текст')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Создано')

    class Meta:
        verbose_name = "Комментарий"
        verbose_name_plural = "Комментарии"

    def __str__(self):
        return "Комментарии для {}".format(self.blog.title)

Homework#1/main/forms.py
from django import forms
from .models import Blog, ImagesForBlog

class BlogForm(forms.ModelForm):
    class Meta:
        model = Blog
        fields = ('title','description')

class ImagesForBlogForm(forms.ModelForm):
    class Meta:
        model = ImagesForBlog
        fields = ('image','blog')

Homework#1/main/views.py
from django.shortcuts import render, redirect
from django.views.generic import View, ListView
from .models import Blog, ImagesForBlog, CommentsForBlog
from django.core.paginator import Paginator
from .forms import BlogForm,ImagesForBlogForm


def delete_blog(request,blog):
    Blog.objects.get(pk=blog).delete()
    return redirect('main:home')


def delete_image(request,image,blog):
    ImagesForBlog.objects.get(pk=image).delete()
    return redirect('main:editblog', blog)


class Main(View):
    template_name = 'main.html'


    def get(self, request, *args, **kwargs):
        blogs = []
        for blog in Blog.objects.all():
            blogs.append({
                'data': blog,
                'images': ImagesForBlog.objects.filter(blog=blog.id),
            })
        for blog in blogs:
            blog['comments'] = reversed(CommentsForBlog.objects.filter(blog=blog['data'].id))

        page = request.GET.get('page')
        if not page:
            page = 1

        p = Paginator(list(reversed(blogs)), 3)

        return render(request, self.template_name, {
            'page': 'home',
            'title': 'Блог | Главная',
            'blogs': p.page(page),
            'blogForm': BlogForm,
            'imagesForBlogForm': ImagesForBlogForm,
            'pagnav': p.page_range
        })

    def post(self,request, *args, **kwargs):
        if request.POST.get('is_comment', False):
            comment = CommentsForBlog(blog=Blog.objects.get(pk=request.POST['blog']), user=request.user, text=request.POST['text'])
            comment.save()
            return redirect('main:home')
        else:
            blog = Blog(title=request.POST['title'], description=request.POST['description'])
            blog.save()
            if request.FILES:
                for img in request.FILES.keys():
                    image = ImagesForBlog(image=request.FILES[img], blog=blog)
                    image.save()
            return redirect('main:home')

class EditBlog(View):
    template_name = 'blog/edit.html'

    def get(self, request, blog, *args, **kwargs):
        blog = Blog.objects.get(pk=blog)
        return render(request,self.template_name, {
            'title': 'Блог | {}'.format(blog.title),
            'blog': blog,
            'images': ImagesForBlog.objects.filter(blog=blog)
        })

    def post(self, request, blog, *args, **kwargs):
        b = Blog.objects.get(pk=blog)
        b.title = request.POST['title']
        b.description = request.POST['description']
        b.save()
        if request.FILES:
            for img in request.FILES.keys():
                image = ImagesForBlog(image=request.FILES[img], blog=b)
                image.save()
        return redirect('main:home')

Homework#1/main/templates/forms/blog.html
<h2>Добавление поста <a href="#" class="btn btn-warning mb-2" onclick="openBlogForm(this)">Развернуть</a></h2>
<form method="POST" action="{% url 'main:home' %}" enctype="multipart/form-data" hidden id="blogform">
    {% csrf_token %}
    <p class="form-group">
        <input type="text" name="title" placeholder="Заголовок" class="form-control">
    </p>
    <p class="form-group">
        <textarea name="description" id="" cols="30" rows="10" class="form-control">Описание...</textarea>
    </p>
    <div id="images" class="form-group">
        <span class="btn btn-file"><input type="file" name="image1" class="form-control-file"></span>
    </div>
    <a onclick="addFileInputForm()" href="#" class="btn btn-light" style="box-shadow: 1px 1px 2px black">Еще</a>
    <input type="submit" class="btn btn-success" value="Добавить" style="box-shadow: 1px 1px 2px black">
</form>
<script>
    function addFileInputForm() {
        block = document.getElementById('images');
        block.innerHTML += '<span class="btn btn-file"><input type="file" name="image'+((block.querySelectorAll('input')).length + 1)+'" class="form-control-file"></span>';
    }
    function openBlogForm(elem) {
        is_hidden = document.getElementById('blogform').hidden;
        if (is_hidden){
            document.getElementById('blogform').hidden = false;
            elem.innerHTML = 'Свернуть'
        } else {
            document.getElementById('blogform').hidden = true;
            elem.innerHTML = 'Развернуть'
        }
    }
</script>

Homework#1/main/templates/forms/editblog.html
<form action="{% url 'main:editblog' blog.id %}" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <p class="form-group">
        <input type="text" name="title" value="{{ blog.title }}" class="form-control">
    </p>
    <p class="form-group">
        <textarea name="description" id="" cols="30" rows="10" class="form-control">{{ blog.description }}</textarea>
    </p>
    <div id="images" class="form-group">
        <span class="btn btn-file"><input type="file" name="image1" class="form-control-file"></span>
    </div>
    <a onclick="addFileInputForm()" href="#" class="btn btn-light mb-3" style="box-shadow: 1px 1px 2px black">Еще</a>
    {% for img in images %}
        <p>
            <img src="/{{ img.image.url }}" alt="" width="100" style="border-radius: 15px; box-shadow: 2px 2px 3px black">
            <a href="{% url 'main:deleteimage' blog.id img.id%}" class="btn btn-danger">X</a>
        </p>
    {% endfor %}
    <input type="submit" class="btn btn-light" value="Изменить">
</form>
<script>
    function addFileInputForm() {
        block = document.getElementById('images');
        block.innerHTML += '<span class="btn btn-file"><input type="file" name="image'+((block.querySelectorAll('input')).length + 1)+'" class="form-control-file"></span>';
    }
</script>